### ISSUE TITLE
proc address prototype

### ISSUE THREAD

**Issue by chriscamacho** [BindBC/bindbc-opengl#1]
else version(Posix) {
        enum getCurrentContextName = "glXGetCurrentContext";
        enum getProcAddressName = "glxGetProcAddress";
    }

should be gl**X**GetProcAddress or you get a bad lbrary error!

**Comment by mdparker** [comment]
Thanks!

**Comment by chriscamacho** [comment]
my pleasure, really the least I could do, great work.... (bindbc has a great future I'm sure!)
