### ISSUE TITLE
OpenGL ES?

### ISSUE THREAD

**Issue by Member1221** [BindBC/bindbc-opengl#11]
Is there any tag for OpenGL ES support, I get errors when creating shaders when using the GL_33 version for OpenGL ES.

Note: The device im trying to use it on supports OpenGL ES 2 (but ES 2 supports the GL 3.3 features I use afaik, that being vbos, vaos and shaders)

**Comment by mdparker** [comment]
No. There is a [DerelictGLES binding](https://github.com/DerelictOrg/DerelictGLES/issues) (which never saw that much use as far as I'm aware) that I haven't yet ported over to BindBC, but once I do it will be available as bindbc-gles. It's not high on the list of packages remaining to port over, though.

**Comment by Member1221** [comment]
Ah, in that case I could take up porting it over at some point. Though why not intergrate it in to bindbc-opengl? It's still OpenGL after all.

**Comment by mdparker** [comment]
No, it's not OpenGL. They have separate headers on the C side, separate libraries, and there's also EGL to be concerned with, plus the different approaches to getting access to it on different devices. Combining it with the ogl binding would be needless complexity.

**Comment by Member1221** [comment]
Okay. Thanks for answering my question, i'll close the issue now :)
