### ISSUE TITLE
Nvidia extensions

### ISSUE THREAD

**Issue by AODQ** [BindBC/bindbc-opengl#12]
Would be nice to have support for nvidia extension. Specifically the new ones such as NV_command_list, NV_mesh_shader, NV_shading_rate_image, etc.

Will attempt to make a fork of this with nvidia support, though I'll probably only write the specific extensions I'm interesting in.

**Comment by mdparker** [comment]
Yes, I intend to implement support for a great many extensions, just as I did in Derelict. It's just a matter of time and priorities. I'll see about adding some NV extensions this weekend.

**Comment by AODQ** [comment]
I have added some NVIDIA extensions right now
NV_command_list, NV_shader_buffer_load, & NV_shader_buffer_unified_memory
https://github.com/aodq/bindbc-opengl

I'm just adding them in as I need them though.

**Comment by mdparker** [comment]
Once you've got all of the ones you need added in, I'd appreciate a pull request!
