### ISSUE TITLE
glClearNamedFramebufferfi is missing a parameter

### ISSUE THREAD

**Issue by henrygouk** [BindBC/bindbc-opengl#14]
See reference: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glClearBuffer.xhtml

Looks like the `drawBuffer` parameter is missing in the bind-bc bindings.

**Comment by mdparker** [comment]
Thanks! I'll fix this soonish.

**Comment by mdparker** [comment]
Fixed in 0.10.0.
