### ISSUE TITLE
Clarification: OpenGL context is needed, but can it change?

### ISSUE THREAD

**Issue by moon-chilled** [BindBC/bindbc-opengl#15]
Docs say you have to make an OpenGL context before you call `loadOpenGL()`.  If I destroy that context and make a new one, will the loaded functions continue to work?

**Comment by mdparker** [comment]
That's system-dependent. In theory, you can't rely on it. In practice, the last time I looked into it (a few years back), it shouldn't matter on Linux and Mac. On Windows, it is supposedly only a problem IIRC if the pixel format of the new context is different from the old one. You'll need to dig into the relevant platform-specific documentation out there to see what the state of things is today.

Anyway, the safe bet is to always reload the functions after creating a new context.

**Comment by moon-chilled** [comment]
Cool, thank you.  Probably would be a good idea to note that in the docs.

**Comment by moon-chilled** [comment]
Just to be clear, I can just call `loadOpenGL()` again and it will reload the functions?
