### ISSUE TITLE
Update loader

### ISSUE THREAD

**Issue by Superbelko** [BindBC/bindbc-opengl#18]
It is currently giving an error when trying to use opengl and glfw.

just add both
```
dub add bindbc-glfw
dub add bindbc-opengl
```

and we've got an error

```
Unresolvable dependencies to package bindbc-loader:
  bindbc-glfw 0.10.0 depends on bindbc-loader ~>0.3.0
  bindbc-glfw 0.10.0 depends on bindbc-loader ~>0.3.0
  bindbc-opengl 0.12.0 depends on bindbc-loader ~>0.2.1
```

**Comment by mdparker** [comment]
I'll be updating all the packages to use version 0.3.0 eventually. I didn't want to tag new releases just to update the loader dependency. For now, you should be able to just specify ~>0.3.0 in your project's `dub.selections.json`.

**Comment by Superbelko** [comment]
Unfortunately this doesn't seems to work. It spits same error on dub build. 
I understand your motivation, so changing the loader version in dub cache seems to work for now.

**Comment by mdparker** [comment]
Okay. Since the dub.selections thing doesn't work, I've gone ahead and pushed an update. Upgrade to 0.13.0 for the fix.

Thanks!
