### ISSUE TITLE
Please support ARB_sparse_texture, ARB_sparse_texture2, and ARB_sparse_texture_clamp

### ISSUE THREAD

**Issue by tsbockman** [BindBC/bindbc-opengl#22]
Sparse textures are important for the modern AZDO style, and for efficient level of detail control. I have submitted a pull request: https://github.com/BindBC/bindbc-opengl/pull/21

**Comment by mdparker** [comment]
Available along with the `@nogc nothrow has*` in 0.15.0. Thanks!
