### ISSUE TITLE
Support of GL_SHADING_LANGUAGE_VERSION​

### ISSUE THREAD

**Issue by Fr3nchK1ss** [BindBC/bindbc-opengl#24]
In my code, trying to use a line like 
```
import bindbc.opengl;
...
info ("OpenGL version: " ~ to!string(glGetString(GL_SHADING_LANGUAGE_VERSION​)));
```

yields 
```
source/dterrent/system/window.d(123,58): Error: char 0x200b not allowed in identifier
source/dterrent/system/window.d(123,58): Error: character 0x200b is not a valid token
```
Grepping around bindbc-opengl, I can not find any occurrence of GL_SHADING_LANGUAGE_VERSION​ ([Khronos reference page](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetString.xhtml)). Should be defined in file [gl20.d](https://github.com/BindBC/bindbc-opengl/blob/master/source/bindbc/opengl/bind/gl20.d) I think, as [GLSL version is defined from OpenGL 2.0](https://en.wikipedia.org/wiki/OpenGL_Shading_Language#Versions).

**Comment by mdparker** [comment]
`GL_SHADING_LANGUAGE_VERSION` is [defined on line 91 of gl20.d](https://github.com/BindBC/bindbc-opengl/blob/master/source/bindbc/opengl/bind/gl20.d#L91).  

I can't see how those error messages have anything to do with that symbol. Can you post a minimal version of your code that demonstrates the error?

**Comment by Fr3nchK1ss** [comment]
Alright,
I put the blame on bindbc becoz the error column matched that const var + a grep -iIR on bindbc-opengl did not return the definition of GL_SHADING_LANGUAGE_VERSION.

Googling that error :
> U+200B is: ZERO WIDTH SPACE. Somehow you got that invisible character 
> into your code. You have to get rid of it.

A zero width space (whatever it is) creeped into my Atom editor & into the terminal console by copy/paste. I just copy/pasted yesterday's shell command in an online unicode decoder and I do get:
`grep%20-iIR%20GL_SHADING_LANGUAGE_VERSION%u200B`
instead of
`grep%20-iIR%20GL_SHADING_LANGUAGE_VERSION`

Fun fact : you can try it yourself by copy pasting my first post above in a [unicode decoder](https://www.online-toolz.com/tools/text-unicode-entities-convertor.php).  You will see %u200B was there.

Much sorry mdparker. Issue can be killed.

**Comment by Fr3nchK1ss** [comment]
I updated the issue. Much sorry and thanks for your time / lib.
Fr3nchK1ss

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mdparker** [comment]
No worries. Glad you got it solved,
