### ISSUE TITLE
Only OpenGL 1.1 can be loaded on intel intergrated graphics

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [BindBC/bindbc-opengl#26]
It appears this bindings fail loading anything over OpenGL 1.1 on Intel Intergrated Graphics.

```d
import bindbc.sdl;
import bindbc.opengl;
import std.stdio;

/**
    Opens Window
*/
void main() {
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, 0);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GLcontextFlag.SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);
    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
    SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
    SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);
    window = SDL_CreateWindow("Test App", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 1024, 1024, SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE);
    
    gl_context = SDL_GL_CreateContext(window);
    SDL_GL_MakeCurrent(window, gl_context);
    SDL_GL_SetSwapInterval(1);

    // Load GL 3
    GLSupport support = loadOpenGL();
    switch(support) {
        case GLSupport.noLibrary:
            throw new Exception("OpenGL library could not be loaded!");

        case GLSupport.noContext:
            throw new Exception("No valid OpenGL context was found!");

        default: break;
    }

    import std.string : fromStringz;
    writefln("GLInfo:\n\t%s\n\t%s\n\t%s\n\tgls=%s",
        glGetString(GL_VERSION).fromStringz,
        glGetString(GL_VENDOR).fromStringz,
        glGetString(GL_RENDERER).fromStringz,
        support
    );
    
    // attempting to access glCreateShader causes the app to crash due to null pointer reference.
}

static this() {
    loadSDL();

    SDL_Init(SDL_INIT_EVERYTHING);
}
```

Output on some devices using Intel iGPUS:
```
GLInfo:
        3.2.0 - Build 27.20.100.8681
        Intel
        Intel(R) UHD Graphics 630
        gls=gl11
```

```
GLInfo:
        3.2.0 - Build 10.18.10.5161
        Intel
        Intel(R) HD Graphics 4000
        gls=gl11
```

While the GL_VERSION string says GL 3.2 is supported, the support returned by loadOpenGL only returns gl11

**Comment by rikkimax** [comment]
>        3.2.0 - Build 10.18.10.5161

Errrm that driver is old

**Comment by LunaTheFoxgirl** [comment]
It is, newer drivers were attempted later with the same result

**Comment by mdparker** [comment]
Did you specify version `GL_32` in your dub package or compiler command line? If no version is specified, the loader will only load GL 1.1 by default.

**Comment by mdparker** [comment]
Which platform are you on?

**Comment by LunaTheFoxgirl** [comment]
Problem happens on Windows and Linux

**Comment by mdparker** [comment]
Unfortunately, I have no idea what, if anything, I can do from my end. The basic approach to loading the functions is the same I've been using ever since I first implemented DerelictGL in 2004. It's the same approach used by OpenGL loaders in the C world, like GLEW.

And now, after doing some digging, I've found others in the Intel forums having what appears to be the same problem:

https://community.intel.com/t5/Developing-Games-Graphics-on/Intel-HD-Graphics-3000-and-4000-reports-GDI-driver/td-p/1094299

So it seems there may be nothing anyone can do about it.

**Comment by mdparker** [comment]
Here's another thread from DisplayLink users reporting the same:

https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/17299984-i-need-full-opengl-support

One user posted the following in the thread in 2020:

> Going to multiple display settings,
> and instead of choosing "Show only on 2" (the external dynadocked monitor)
> I selected "duplicate these displays"...
‪> eh Voilà !
>
> I now have OpenGL 4.X support on my external docked monitor !!!

I don't know if that has any relation to what your users are experiencing, but so far it's the only thing I've found that verifies a working solution.

**Comment by sanket143** [comment]
Also fails for me, I'm on Arch Linux

```
GLInfo:
        4.6 (Compatibility Profile) Mesa 21.2.0
        Intel
        Mesa Intel(R) HD Graphics 520 (SKL GT2)
        4.60
        gls=gl33
Segmentation fault (core dumped)
```

**Comment by mdparker** [comment]
@sanket143 The OP didn't have a segfault. Are you sure it's the same issue? Did you check which version of OpenGL is being loaded by the loader?

**Comment by sanket143** [comment]
oh, so sorry right. it's different. :grimacing:

**Comment by LunaTheFoxgirl** [comment]
I found the root issue, OpenGL will fail to load on intel if you use some extensions + if you use backwards compatible mode. OpenGL will only work in core profile with minimal extensions on intel GPUs.
