### ISSUE TITLE
bindbc-opengl with glu* functions

### ISSUE THREAD

**Issue by vitalfadeev** [BindBC/bindbc-opengl#27]
OpenGL GLU functions:
gluNewTess();
gluTessCallback();
gluTessProperty();
gluTessNormal();

Is possible ?

**Comment by mdparker** [comment]
I see you have created DerelictGLU. Why not switch that to use bindbc-loader and bindbc-opengl?

**Comment by vitalfadeev** [comment]
> I see you have created DerelictGLU. Why not switch that to use bindbc-loader and bindbc-opengl?
Thank for bindings, Mike.

I porting  C source for rendering text on GPU via OpenGL.
C code contains `glu` code from GLUT library.
I do search ``glu + source:D` and found Derelict-module. Old version.
I make Derelict module.

I using bindbc, but not understand how it load bindings. 
In derelict i see abstract class Loader.
Can you tech me about binding process in bindbc ?
Can you write block diagram ?
IIt will be interested for other peolpes, can you describe lbinding process in documentation ?

Real task: have C-code with glu, how to create bindbc-glu module ?

**Comment by mdparker** [comment]
I don't know what good a block diagram would do. All that's required is to declare the appropriate types and function pointers, then load the DLL. The process is very similar to how it's done in Derelict. All of the bindings in the bindbc repositories are examples of how to do it.

Anyway, there aren't a lot of functions in the GLU API (it's not GLUT, by the way, GLUT is something completely different). I guess I can add a module to bindbc-opengl that can be enabled at compile time.

As far as I know, though, GLU is a dead API. Do drivers even provide an implementation any more?

**Comment by vitalfadeev** [comment]
> I don't know what good a block diagram would do. All that's required is to declare the appropriate types and function pointers, then load the DLL. The process is very similar to how it's done in Derelict. All of the bindings in the bindbc repositories are examples of how to do it.
> 
> Anyway, there aren't a lot of functions in the GLU API (it's not GLUT, by the way, GLUT is something completely different). I guess I can add a module to bindbc-opengl that can be enabled at compile time.
> 
> As far as I know, though, GLU is a dead API. Do drivers even provide an implementation any more?

I beginner in OpenGL.
Yes, thank! GLU not GLUT.
GLU is set of functions to create texture mipmaps from a base image, map coordinates between screen and object space, and draw quadric surfaces.
GLUT is window system independent toolkit for writing OpenGL programs. It implements a simple windowing application programming interface.

I reading this idea for font rendering in GPUI: https://developer.nvidia.com/gpugems/gpugems3/part-iv-image-effects/chapter-25-rendering-vector-art-gpu

and check this implementation: https://github.com/sinf/glsl_bezier_font
it uses GLU.
Of course i port this implementation as is, with gluNewTess, gluTessCallback, gluDeleteTess. I see what it not touch OpenGL and can br rewriten. But, of course, always wanted to copy C-code and just reuse it.

Now I think tol rewrite code.
Thank, Mike.
