### ISSUE TITLE
Undefined identifiers

### ISSUE THREAD

**Issue by ZephaniahNoah** [BindBC/bindbc-opengl#34]
I am trying to compile [this](https://github.com/dkorpel/glfw-d/blob/master/examples/triangle-gl/app.d) glfw example which uses bindbc-opengl. When I compile the example I get these errors.
```
src/app.d(55,9): Error: undefined identifier `glBindVertexArray`
src/app.d(135,5): Error: undefined identifier `glGenVertexArrays`
src/app.d(136,5): Error: undefined identifier `glBindVertexArray`
/usr/bin/dmd failed with exit code 1.
```
Is the example wrong? Or am I doing something wrong? Or is this a bindbc-opengl issue?

**Comment by mdparker** [comment]
I can't even begin to guess why that's happening without more information. Looks like you've got a configuration problem somewhere. Are you using the dub.sdl in the linked repository, or a custom one?

**Comment by ZephaniahNoah** [comment]
I am using a custom dub.json.
```json
{
	"dependencies": {
		"bindbc-opengl": "~>0.13.0",
		"glfw-d": "~>1.1.0"
	},
	"description": "Hello World - A minimal DUB bundle.",
	"name": "testopengl",
	"subConfigurations": {
		"bindbc-opengl": "dynamicBC"
	}
}
```
I just found what I missed.. I added this to the dub and it works.
```json
	"versions": [
		"GL_31"
	]
```
My bad :man_facepalming:

**Comment by mdparker** [comment]
Ah, I feel silly now. I always forget that the default configuration is for GL 2.1. Your missing functions are in GL 3.0 and higher, so yeah, you need at least GL_30 for those. I should just change the default.
