### ISSUE TITLE
glGetInteger64v takes "__GLsync*" instead of uint (GLenum)

### ISSUE THREAD

**Issue by HuskyNator** [BindBC/bindbc-opengl#36]
When I try to get the value of `GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET`, the compiler complains I need to pass in a `__GLsync*` instead. I can cast to it & hope for the best but am unsure what __GLsync* even means.

```d
GLint64 a;
glGetInteger64v(GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET, &a);
a.writeln;
```

**Comment by mdparker** [comment]
That was a typo in the function declaration. Should work in version 1.0.3 once the registry updates.
