### ISSUE TITLE
Fails to load modern OpenGL on Asus TUF F15 laptop with discrete GPU

### ISSUE THREAD

**Issue by rillki** [BindBC/bindbc-opengl#39]
It is a gaming laptop and it has a discrete GPU. It loads gl11 only and fails to load modern OpenGL. Games do work on this laptop. For example, Minecraft works fine. 

Do you have any ideas on how to solve this issue?

**Comment by ichordev** [comment]
Hey, it's gonna be tough to diagnose without a little more info. _(For instance, Minecraft comes with its own OpenGL binaries; even if you linked with those, you would be dependant on everyone who uses your application having Minecraft installed!)_
- What operating system do you run?
- Where do you have OpenGL's dynamic libraries (.dll/.dylib/.so) installed on your system?
- What errors are you getting from bindbc-loader when you try to load OpenGL? (using `bindbc.loader.errors`)

**Comment by rillki** [comment]
> Hey, it's gonna be tough to diagnose without a little more info. _(For instance, Minecraft comes with its own OpenGL binaries; even if you linked with those, you would be dependant on everyone who uses your application having Minecraft installed!)_
>
> * What operating system do you run?
> * Where do you have OpenGL's dynamic libraries (.dll/.dylib/.so) installed on your system?
> * What errors are you getting from bindbc-loader when you try to load OpenGL? (using `bindbc.loader.errors`)

Thank you for quick reply! To answer your questions:

I have created a simple [D/GLFW/OpenGL project](https://github.com/rillki/d-glfw-opengl-project-template) and have already tested it on my Windows 10 PC. It works as it should. 

I load libraries dynamically. I have only `glfw3.dll` that I specify where to find - `libs` directory in project folder. Apart from that, it should try to load the system local OpenGL DLL library. 

I face the strange issue described above only on my laptop. It runs Windows 10 as well. 

`opengl32.dll` is located in:
* C:\Windows\system32
* C:\Windows\SysWOW64
* and some other places...

The app successfully compiles and runs - it displays a window, - but modern OpenGL isn't loaded according to `GLSupport`. It returns `gl11`. `bindbc.loader.errors` is empty. 

------------------------
### !!! That is strange... I tried getting OpenGL version directly from `glGetString(GL_VERSION)` and it returns `3.3.0`! It seems that `bindbc-opengl` fails to recognize the version it loads...

**Comment by ichordev** [comment]
You’re getting `gl11`? That means that it *should be* loaded. Just to check, you do have `GL_33` in your versions list right? Otherwise it could be some error with the bindings perhaps—I haven’t had time to investigate the inner-workings of this bindbc library just yet, but I can have a deeper look if it’s still not working for you. :)

**Comment by mdparker** [comment]
@rillki I cloned your repository on my Windows 10 PC, built it, and ran it. It works as expected as it does on your PC.

Is that the same code that's only loading gl11 on your laptop?

**Comment by rillki** [comment]
I close this issue since it seems this is not a library problem.
