### ISSUE TITLE
Add support for opengl 2

### ISSUE THREAD

**Issue by trikko** [BindBC/bindbc-opengl#4]
Now only opengl3 is supported and I have to use derelict-gl instead.

**Comment by mdparker** [comment]
It's already there. OpenGL 1.0 - 2.1 are loaded by default if you don't specify a higher version, minus the deprecated stuff, of course. And FYI, I've begun adding the deprecated stuff. I just need to go through the spec and make sure I'm accurate. Never actually did that with DerelictGL.

**Comment by trikko** [comment]
That's good. I think some "deprecated" features are not actually "deprecated" in opengl 2.1 but only since 3.0.
I've opened a bug just to be sure to be notified when this will be done :+1:

**Comment by mdparker** [comment]
Should be all set with version 0.4.0. Please let me know if you encounter any issues.

**Comment by mdparker** [comment]
Oh, TL;DR -- just add the version identifier `GL_AllowDeprecated` to your version set.

**Comment by trikko** [comment]
Good news. It will be added on next version of vasaro with bindbc-sdl :+1:

**Comment by trikko** [comment]
I'm trying to switch from derelict to bindbc-opengl.
Something went work :)

First: libgl has some problems. Derelict loads "libgl.so.1, libgl.so". BindBC "libgl.so", "libgl.so.1".  If i switch order for bindbc, opengl is loaded.

After the switch I have another problem:

I use: versions "GL_21" "GL_AllowDeprecated" on my dub.sdl

Example:
```d
   context = SDL_GL_CreateContext(renderWindow);
   writeln("CTX: ", openGLContextVersion);

   GLSupport glRet = loadOpenGL();
   if (!isOpenGLLoaded) assert(0, "Error loading opengl support.");

   writeln("CTX: ", openGLContextVersion);
   writeln("GL support: ", glRet);
   writeln("Context: ", context != null);
   writeln("glMatrixMode: ", glMatrixMode);
```
 
output:

```
CTX: noLibrary
CTX: gl45
GL support: gl21
Context: true
glMatrixMode: null
```
It seems that glMatrixMode is not bound.
What's wrong with this code?

PS: Is it possible to bound all function to a draft function that calls assert(0, "not bound")?
So if i use one of those functions before load or something goes wrong (link here) I catch the problem...

**Comment by trikko** [comment]
About "linking" order, I don't have any clue.

About glMatrixMode: this functions (with many others) was deprecrated when pipeline was added to opengl (3.0+). This function is not deprecated in gl 2.0. I think it can't be replaced by any other gl2 functions.

On bindbc this functions is in dep.gl11 module but it should be available for any version < 3.0

**Comment by mdparker** [comment]
> First: libgl has some problems. Derelict loads "libgl.so.1, libgl.so". BindBC "libgl.so", "libgl.so.1". If i switch order for bindbc, opengl is loaded.

OK, I'll switch it up.


> ```
> CTX: noLibrary
> CTX: gl45
> GL support: gl21
> Context: true
> glMatrixMode: null
> ```
> It seems that glMatrixMode is not bound.
> What's wrong with this code?

You've created a 4.5 context. The deprecated functions will have been removed. You need to force a 2.1/3.0 context, or a (IIRC) 3.2 compatibility context for the deprecated functions to be available.

> 
> PS: Is it possible to bound all function to a draft function that calls assert(0, "not bound")?
> So if i use one of those functions before load or something goes wrong (link here) I catch the problem...

That's a road I really don't want to go down as I don't think it should be implemented in a raw binding.

**Comment by trikko** [comment]
I call:
   SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
   SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 1);

Before creating context and window.
What's wrong then? How did that work on derelict?

**Comment by mdparker** [comment]
I just realized you're checking for errors the wrong way. `isOpenGLLoaded` tells you only that some version of OpenGL successfully loaded. The error handling API in `bindbc-loader` can tell you if any functions failed to load.

I can see now I'm going to have to expand the `GLSupport` enum to indicate successful loading of deprecated functions. I'll try to get some work done on improving things within the next couple of days.

> On bindbc this functions is in dep.gl11 module but it should be available for any version < 3.0 

Of course. I can see that you and I are talking about OpenGL versions in different ways. You are treating each version independently, i.e. when you say "OpenGL 2.1" you are referring to the API as it is defined in the 2.1 specification. I've found that in most conversations I've had about OpenGL, that's not how most people think of it (except when explicitly referring to the specification). `GL_21` in BindBC terms means the set of functions that were present in OpenGL 2.1 and are still present in core OpenGL right now. That's why I make the distinction between that set of functions and the deprecated set.

**Comment by mdparker** [comment]
> The error handling API in bindbc-loader can tell you if any functions failed to load.
Sorry, to clarify, for the OpenGL bindings, any functions up to 1.1 on Windows and Linux/BSD, but all versions on Mac. 1.2+ uses a different loader everywhere except Mac.

**Comment by mdparker** [comment]
> I call:
> SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
> SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 1);
> 
> Before creating context and window.
> What's wrong then? How did that work on derelict?

It has nothing to do with Derelict. Looks like [you need this line](http://wiki.libsdl.org/SDL_GLprofile):

    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_COMPATIBILITY);

**Comment by mdparker** [comment]
Actually, it's a bug. I have an extra underscore in a version check: `GL_Allow_Deprecated` instead of `GL_Allow_Deprecated`. Fixing now.

**Comment by trikko** [comment]
Great! Now it works. However there is a problem with bindbc-sdl, I'll open another issue there :)

IMHO GL_20 should mean "load opengl @ 2.0 compatibility level".
Let's say we have a library to draw polygons:
- v1: drawPoint()
- v2: deprecate drawPoint() there is drawLine()!
- v3: deprecate drawLine() there is drawPoly()!

If I understand correctly your interpretation, if i want to use v2, and I load POLY2, I can't draw anything, because I need drawLine() that is deprecated in v3. So I have to load deprecated function that in turn loads drawPoint() that I don't need (i'm using v2).
I think it's better if POLY2 load drawLine() and doesn't load drawPoint(). If i want to use drawPoint() I should call loadDeprecated...

The same happens with opengl2. I can't draw anything if I can't use GL2 functions that are deprecated on GL3+.

Abound unbound functions, i meant something like this: https://run.dlang.io/is/jbyTGq
Doesn't it work for bindbc?
