### ISSUE TITLE
importing bindbc.opengl causes symbol conflicts with stdout

### ISSUE THREAD

**Issue by AndrejMitrovic** [BindBC/bindbc-opengl#41]
Simple test-case:

```D
import std.stdio;
import bindbc.opengl;

void main()
{
    write("Edit source/app.d to start your project.");
    stdout.flush();
}
```

> $ dub
> source/app.d(7,5): Error: function `std.stdio.makeGlobal!"core.stdc.stdio.stdout".makeGlobal` at /home/drey/dlang/dmd-2.101.2/linux/bin64/../../src/phobos/std/stdio.d(5192,20) conflicts with variable `core.stdc.stdio.stdout` at /home/drey/dlang/dmd-2.101.2/linux/bin64/../../src/druntime/import/core/stdc/stdio.d(956,25)
source/app.d(7,11): Error: template `makeGlobal(StdFileHandle _iob)()` does not have property `flush`

It's caused by this public import: https://github.com/BindBC/bindbc-opengl/blob/e9e1c9e9783156b40b947f56f5a223cabb0526a8/source/bindbc/opengl/config.d#L9

**Comment by ichordev** [comment]
Why is that even public…
Maybe you could submit a PR? It seems like you’d only have to remove `public` from that import, and maybe import it manually in other modules as needed…

**Comment by mdparker** [comment]
That can be removed entirely. I don't recall putting it there, but it must have been for some writeln debugging in multiple modules I was doing at one point and I just forgot to delete it. Just remove it.
