### ISSUE TITLE
Allow getting SharedLib and calling bindGLSymbol

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [BindBC/bindbc-opengl#44]
In some instances a user may want to, without having to wait for this package, use an OpenGL extension. It'd be nice if you could just call bindGLSymbol yourself with the SharedLib handle.

**Comment by ichordev** [comment]
I would recommend using the functions in bindbc.loader over `bindGLSymbol`, which clearly isn’t really meant for general use
