### ISSUE TITLE
Update bindbc-loader dependency

### ISSUE THREAD

**Issue by rikkimax** [BindBC/bindbc-opengl#47]
Looks like bindbc-loader is up to version 1.1.5, and it is causing problems for people.

https://forum.dlang.org/post/ygwwpclcuxxrjqsumgtn@forum.dlang.org

**Comment by ichordev** [comment]
This issue has been solved for 9 months: https://github.com/BindBC/bindbc-opengl/commit/a45c046be96c6ca0cf85858221a1593135474602
