### ISSUE TITLE
Release new version for conflicting declarations fix

### ISSUE THREAD

**Issue by dkorpel** [BindBC/bindbc-opengl#8]
I stumbled on duplicate definitions that were fixed in [this commit](https://github.com/BindBC/bindbc-opengl/commit/99b72d1e74a2ce4ed29dff6843909980af037745), but using the newest version 0.6.0 I don't get that fix. Can a new version be released?

**Comment by mdparker** [comment]
Hmm. Now I wonder if I simply forgot to tag a new release or if I was intending to do something else. 

Anyway, thanks for letting me know. I've tagged 0.7.0. It will be available as soon as the dub registry picks it up.
