### ISSUE TITLE
GL_ARB_texture_filter_anisotropic doesn't define GL_TEXTURE_MAX_ANISOTROPY

### ISSUE THREAD

**Issue by WebFreak001** [BindBC/bindbc-opengl#9]
It seems that it checks for `ARB_texture_filter_anisotropic` instead of `GL_ARB_texture_filter_anisotropic` (with GL_` when defining the enum values, so you can't use it using that version

**Comment by mdparker** [comment]
`GL_TEXTURE_MAX_ANISOTROPY` is declared on line 53 of core_46.d. And, sorry, but I don't understand what you're saying about `ARB_texture_filter_anisotropic`.

**Comment by WebFreak001** [comment]
I defined `GL_ARB_texture_filter_anisotropic` as version (like on the wiki) but the symbol isn't found then.

I have to define `ARB_texture_filter_anisotropic` as version for it to work, which is inconsistent with the other symbols and the wiki

**Comment by mdparker** [comment]
Ah, I see. It's the same for `ARB_polygon_offset_clamp` in the same file. I forgot the `GL_` is prefixed everywhere else.

**Comment by mdparker** [comment]
Fixed in 0.7.1. Thanks!
